//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "visit_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub uuid: Option<String>,
    pub uri: String,
    pub method: String,
    pub param: String,
    pub behavior: Option<String>,
    pub content: Option<String>,
    pub remark: Option<String>,
    pub ip: Option<String>,
    pub ip_source: Option<String>,
    pub os: Option<String>,
    pub browser: Option<String>,
    pub times: i32,
    pub create_time: DateTime,
    pub user_agent: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
